### PR TITLE
Create main.emojic

### PR DESCRIPTION
**Pull request by KaiDevrim**

### CODE REVIEW

**Review by willdoescode — CHANGES_REQUESTED** [review]
remove !

**Comment by aidenybai** [comment]
never

**Comment by aidenybai** [comment]
emojic is a real language that real developers use

**Comment by aidenybai** [comment]
peeporiot

**Comment by willdoescode** [comment]
yes emojicode has memory management and other things

**Comment by KaiDevrim** [comment]
MERGE IT

**Comment by KaiDevrim** [comment]
MERGE THE BRNACH

**Comment by KaiDevrim** [comment]
@willdoescode

**Comment by KaiDevrim** [comment]
IF YOU NO MERGE BRNACH THEN WILL DOES NOT CODE

**Comment by okdargy** [comment]
@KaiDevrim Just get rid of the ! and he will merge it. It's that simple.

**Comment by KaiDevrim** [comment]
ok will get rid of man

**Comment by KaiDevrim** [comment]
@willdoescode merge or i will eat your pasta

**Pull request merged**
